//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTracker_comp2007.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public int Id { get; set; }
        public string homeName { get; set; }
        public string awayName { get; set; }
        public int homePoints { get; set; }
        public int awayPoints { get; set; }
        public int attendances { get; set; }
        public string stadium { get; set; }
        public string sportType { get; set; }
        public System.DateTime datePlayed { get; set; }
    }
}
